# Site settings
title: Subject to change
email: dayneko.ab@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: ArtemDayneko
github_username: jamert
highlighter: pygments

# Build settings
markdown: kramdown
